version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gym_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres -c listen_addresses='*'
               -c max_connections=200
               -c shared_buffers=256MB
               -c effective_cache_size=1GB
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - pgnetwork

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pgnetwork

 

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gym_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./logs/php.log:/var/log/fpm-php.www.log
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - pgnetwork

volumes:
  pgdata:

networks:
  pgnetwork: